/**
 * Curated brand whitelist — brands shown on the site.
 * Expanded to cover all SimpleTire-overlapping brands from TireWeb.
 *
 * Brand names are stored UPPERCASED for case-insensitive matching against
 * the API's `make_name` field.
 */

/** Map of UPPERCASED API brand name → local logo filename in /brand-logos/ */
export const CURATED_BRANDS: Map<string, string> = new Map([
  ["ACCELERA", ""],
  ["ACCELUS", ""],
  ["ADVANCE", ""],
  ["AEOLUS", ""],
  ["AG PLUS", ""],
  ["AG PRO", ""],
  ["AG-DURA", ""],
  ["AGSTAR", ""],
  ["AIRLOC", ""],
  ["AKURET", ""],
  ["ALLIANCE", ""],
  ["AMERICAN", ""],
  ["AMERICAN ROAD STAR", ""],
  ["AMERICAN TOURER", ""],
  ["AMERI*STEEL", ""],
  ["AMERICUS", ""],
  ["AMERITREAD", ""],
  ["AMERITYRE", ""],
  ["AMP", ""],
  ["AMULET", ""],
  ["ANTARES", ""],
  ["ANTYRE", ""],
  ["AOSEN", ""],
  ["AOTELI", ""],
  ["APLUS", ""],
  ["APTANY", ""],
  ["ARDENT", ""],
  ["ARISUN", ""],
  ["ARMOHERO", ""],
  ["ARMOUR", ""],
  ["ARMSTRONG", ""],
  ["ARROYO", ""],
  ["ASCENSO", ""],
  ["ASPEN", ""],
  ["ASTRO", ""],
  ["ATF", ""],
  ["ATLANDER", ""],
  ["ATLAS", ""],
  ["ATTURO", ""],
  ["AURORA", ""],
  ["AUTOGRIP", ""],
  ["AUTOGUARD", ""],
  ["AVON", ""],
  ["BCT", ""],
  ["BEARWAY", ""],
  ["BFGOODRICH", "bfgoodrich.png"],
  ["BKT", ""],
  ["BLACK BEAR", ""],
  ["BLACKHAWK", ""],
  ["BLACKLION", ""],
  ["BOTO", ""],
  ["BRIDGESTONE", "bridgestone.png"],
  ["BRIWAY", ""],
  ["BUCKSHOT", ""],
  ["CACHLAND", ""],
  ["CAMBRIDGE", ""],
  ["CAPITOL", ""],
  ["CARAWAY", ""],
  ["CARGOMAX", ""],
  ["CARLSTAR", ""],
  ["CASTLE ROCK", ""],
  ["CAVALIER", ""],
  ["CAVALRY", ""],
  ["CEAT", ""],
  ["CELIMO", ""],
  ["CENTARA", ""],
  ["CENTENNIAL", ""],
  ["CHAOYANG", ""],
  ["COKER", ""],
  ["COMFORSER", ""],
  ["CONCOURS", ""],
  ["CONSTANCY", ""],
  ["CONSTELLATION", ""],
  ["CONTENDER", ""],
  ["CONTINENTAL", "continental.png"],
  ["COOPER", "cooper.png"],
  ["COPARTNER", ""],
  ["CORSA", ""],
  ["COSMO", ""],
  ["COUNTRYWIDE", ""],
  ["CROP MAX", ""],
  ["CROPMASTER", ""],
  ["CROSSMAX", ""],
  ["CROSSWIND", ""],
  ["CST", ""],
  ["CULTOR", ""],
  ["CYCLONE", ""],
  ["DAWG POUND", ""],
  ["DAYTON", ""],
  ["DCENTI", ""],
  ["DEAN", ""],
  ["DEESTONE", ""],
  ["DEFINITY", ""],
  ["DELI", ""],
  ["DELINTE", ""],
  ["DELIUM", ""],
  ["DELTA", ""],
  ["DENMAN", ""],
  ["DEXTERO", ""],
  ["DIABLO", ""],
  ["DIAMONDBACK", ""],
  ["DICK CEPEK", ""],
  ["DIEHARD", ""],
  ["DORAL", ""],
  ["DOUBLE COIN", ""],
  ["DOUBLESTAR", ""],
  ["DOUGLAS", ""],
  ["DUCK COMMANDER", ""],
  ["DUNLOP", "dunlop.webp"],
  ["DURAMAX", ""],
  ["DURATURN", ""],
  ["DURO", ""],
  ["DURUN", ""],
  ["DYNACARGO", ""],
  ["DYNAMAXX", ""],
  ["DYNAMO", ""],
  ["DYNATRAC", ""],
  ["DYNATRAIL", ""],
  ["ECOVISION", ""],
  ["ELDORADO", ""],
  ["ELEVATE", ""],
  ["EVERGREEN", ""],
  ["EVOLUXX", ""],
  ["FALKEN", "falken.png"],
  ["FARM KING", ""],
  ["FARMBOY", ""],
  ["FARROAD", ""],
  ["FEDERAL", ""],
  ["FERENTINO", ""],
  ["FIERCE", ""],
  ["FINALIST", ""],
  ["FIRESTONE", "firestone.png"],
  ["FORCELAND", ""],
  ["FORCEUM", ""],
  ["FORERUNNER", ""],
  ["FORGIATO", ""],
  ["FORTUNE", ""],
  ["FREEDOM HAULER", ""],
  ["FREESTAR", ""],
  ["FULDA", ""],
  ["FULLRUN", ""],
  ["FULLWAY", ""],
  ["FURY", ""],
  ["FUZION", ""],
  ["GALAXY", ""],
  ["GENERAL", "general.png"],
  ["GEO-TRAC", ""],
  ["GEOQUEST", ""],
  ["GEOSTAR", ""],
  ["GFT RIDER", ""],
  ["GINELL", ""],
  ["GIOVANNA", ""],
  ["GISLAVED", ""],
  ["GITI", ""],
  ["GLADIATOR", ""],
  ["GOALSTAR", ""],
  ["GOFORM", ""],
  ["GOLD CROWN", ""],
  ["GOLDWAY", ""],
  ["GOODRIDE", ""],
  ["GOODTRIP", ""],
  ["GOODYEAR", "goodyear.png"],
  ["GRAND SPIRIT", ""],
  ["GREATWAY", ""],
  ["GREEN MAX", ""],
  ["GREENBALL", ""],
  ["GREENTRAC", ""],
  ["GREMAX", ""],
  ["GRENLANDER", ""],
  ["GRI", ""],
  ["GRIPMAX", ""],
  ["GRIT KING", ""],
  ["GRITMASTER", ""],
  ["GROUNDSPEED", ""],
  ["GT RADIAL", ""],
  ["GTK", ""],
  ["HAIDA", ""],
  ["HANKOOK", "hankook.png"],
  ["HARTLAND", ""],
  ["HARVEST KING", ""],
  ["HEADWAY", ""],
  ["HEMISPHERE", ""],
  ["HERCULES", ""],
  ["HERITAGE", ""],
  ["HI-FLY", ""],
  ["HI-RUN", ""],
  ["HOOSIER", "hoosier.png"],
  ["IMPERIAL", ""],
  ["INNOVA", ""],
  ["INTERCO", ""],
  ["INTERSTATE", ""],
  ["INVOVIC", ""],
  ["IRIS", ""],
  ["IRONHEAD", ""],
  ["IRONMAN", ""],
  ["ITP", ""],
  ["JETZON", ""],
  ["JINYU", ""],
  ["JK TYRE", ""],
  ["JOURNEY", ""],
  ["JOYROAD", ""],
  ["K9", ""],
  ["KANATI", ""],
  ["KAPSEN", ""],
  ["KELLY", ""],
  ["KENDA", "kendaTires.png"],
  ["KINFOREST", ""],
  ["KINGSTAR", ""],
  ["KORYO", ""],
  ["KPATOS", ""],
  ["KUMHO", "kumho.png"],
  ["LANCASTER", ""],
  ["LANDE", ""],
  ["LANDFLEET", ""],
  ["LANDGOLDEN", ""],
  ["LANDSAIL", ""],
  ["LANDSPIDER", ""],
  ["LANDY", ""],
  ["LANVIGATOR", ""],
  ["LARAMIE", ""],
  ["LAUFENN", "laufenn.png"],
  ["LEAO", ""],
  ["LEMANS", ""],
  ["LEXANI", ""],
  ["LINGLONG", ""],
  ["LIONHART", ""],
  ["LIZETTI", ""],
  ["LONG MARCH", ""],
  ["MAGNA", ""],
  ["MALHOTRA", ""],
  ["MARK MA", ""],
  ["MARSHAL", ""],
  ["MASTER", ""],
  ["MASTERCRAFT", ""],
  ["MASTERTRACK", ""],
  ["MATRAX", ""],
  ["MAXAM", ""],
  ["MAXDURA", ""],
  ["MAXTREK", ""],
  ["MAXXIS", "maxxis.png"],
  ["MAYRUN", ""],
  ["MAZZINI", ""],
  ["MESA", ""],
  ["MICHELIN", "michelin.png"],
  ["MICKEY THOMPSON", "mickeyThompson.webp"],
  ["MILEKING", ""],
  ["MILEPRO", ""],
  ["MILESTAR", ""],
  ["MINERVA", ""],
  ["MINOS", ""],
  ["MIRADA", ""],
  ["MITAS", ""],
  ["MITCO", ""],
  ["MOMO", ""],
  ["MONTREAL", ""],
  ["MRF", ""],
  ["MRL", ""],
  ["MUD CLAW", ""],
  ["MULTI-MILE", ""],
  ["NAMA", ""],
  ["NANCO", ""],
  ["NANKANG", "nankang.png"],
  ["NATIONAL", ""],
  ["NAVITRAC", ""],
  ["NEGOTIATOR", ""],
  ["NEOTERRA", ""],
  ["NEPTUNE", ""],
  ["NEUTON", ""],
  ["NEXEN", "nexen.png"],
  ["NIKA", ""],
  ["NITTO", "nitto.png"],
  ["NOBLE", ""],
  ["NOKIAN", "nokianTyres.avif"],
  ["NUTECH", ""],
  ["OBOR", ""],
  ["OHTSU", ""],
  ["OMNI", ""],
  ["OMNI CARGO", ""],
  ["OMNI TRAIL", ""],
  ["OMNIMAX", ""],
  ["ONYX", ""],
  ["OTANI", ""],
  ["OTR", ""],
  ["PACEMARK", ""],
  ["PACSTAR", ""],
  ["PANTERA", ""],
  ["PARAGON", ""],
  ["PATRIOT", ""],
  ["PEARLY", ""],
  ["PEGASUS", ""],
  ["PERCHERON", ""],
  ["PERFORMER", ""],
  ["PETLAS", ""],
  ["PINNACLE", ""],
  ["PINSO", ""],
  ["PIRELLI", "pirelli.png"],
  ["POINT S", ""],
  ["POWER KING", "powerKing.png"],
  ["POWERTRAC", ""],
  ["PREDATOR", ""],
  ["PREMIORRI", ""],
  ["PRESA", ""],
  ["PRIMEWELL", ""],
  ["PRIMEX", ""],
  ["PRINX", ""],
  ["PRO COMP", ""],
  ["PROMETER", ""],
  ["PROSTAR", ""],
  ["PROVATO", ""],
  ["QUADBOSS", ""],
  ["RADAR", "radarTires.avif"],
  ["RALSON", ""],
  ["RANGE FINDER", ""],
  ["RAPID", ""],
  ["RBP", ""],
  ["RED DIRT ROAD", ""],
  ["REGENCY", ""],
  ["REGUL", ""],
  ["REMINGTON", ""],
  ["RIKEN", "riken.png"],
  ["ROAD FORCE", ""],
  ["ROADCLAW", ""],
  ["ROADCRUZA", ""],
  ["ROADLUX", ""],
  ["ROADMASTER", ""],
  ["ROADONE", ""],
  ["ROADTRACK", ""],
  ["ROCKBLADE", ""],
  ["RODACO", ""],
  ["ROSAVA", ""],
  ["ROVELO", ""],
  ["ROYAL BLACK", ""],
  ["RUBBERMASTER", ""],
  ["RUNWAY", ""],
  ["RYDANZ", ""],
  ["SAFERICH", ""],
  ["SAFFIRO", ""],
  ["SAILUN", ""],
  ["SAMSON", ""],
  ["SCEPTOR", ""],
  ["SEDONA", ""],
  ["SHINKO", ""],
  ["SIERRA", ""],
  ["SIGMA", ""],
  ["SOLAR", ""],
  ["SOLIDEAL", ""],
  ["SOLIDWAY", ""],
  ["SONAR", ""],
  ["SOTERA", ""],
  ["SPEEDWAYS", ""],
  ["SPORTLINE", ""],
  ["STARFIRE", ""],
  ["STARMAXX", ""],
  ["STARSAIL", ""],
  ["STATEWIDE", ""],
  ["STI", ""],
  ["SUMIC", ""],
  ["SUMITOMO", "sumitomo.png"],
  ["SUMMIT", ""],
  ["SUNFULL", ""],
  ["SUNNY", ""],
  ["SUNTEK", ""],
  ["SUPER A", ""],
  ["SUPERCARGO", ""],
  ["SUPERMAX", ""],
  ["SURETRAC", ""],
  ["SYNERGY", ""],
  ["SYRON", ""],
  ["TACOMA", ""],
  ["TASKMASTER", ""],
  ["TATKO", ""],
  ["TBB TIRES", ""],
  ["TEMPRA", ""],
  ["TESCHE", ""],
  ["THREE-A", ""],
  ["THUNDERER", ""],
  ["TIANLI", ""],
  ["TIMBERLAND", ""],
  ["TIRON", ""],
  ["TITAN", ""],
  ["TORNEL", ""],
  ["TORQUE", ""],
  ["TOURADOR", ""],
  ["TOWSTAR", ""],
  ["TOW-MASTER", ""],
  ["TOYO", "toyo.png"],
  ["TRACGARD", ""],
  ["TRACMAX", ""],
  ["TRAILER KING", ""],
  ["TRAILER MASTER", ""],
  ["TRANSEAGLE", ""],
  ["TRANSMAX", ""],
  ["TRANSPORTER", ""],
  ["TRAVELSTAR", ""],
  ["TRAZANO", ""],
  ["TRELLEBORG", ""],
  ["TRI-ACE", ""],
  ["TRIANGLE", ""],
  ["TRIVANT", ""],
  ["TURNPIKE", ""],
  ["UNICORN", ""],
  ["UNIROYAL", "uniroyal.png"],
  ["UNIVERSAL", ""],
  ["VANDERBILT", ""],
  ["VANGUARD", ""],
  ["VANTAGE", ""],
  ["VEE RUBBER", ""],
  ["VEENTO", ""],
  ["VELOCITY", ""],
  ["VENEZIA", ""],
  ["VENOM POWER", ""],
  ["VERCELLI", ""],
  ["VERSATYRE", ""],
  ["VITOUR", "vitour.png"],
  ["VIZZONI", ""],
  ["VOGUE", "vogue.png"],
  ["VREDESTEIN", "vredestein.webp"],
  ["WANDA", ""],
  ["WANLI", ""],
  ["WATERFALL", ""],
  ["WESTLAKE", ""],
  ["WINDA", ""],
  ["WINDFORCE", ""],
  ["WINDPOWER", ""],
  ["WINRUN", ""],
  ["WOLFPACK", ""],
  ["XCELLENT", ""],
  ["YOKOHAMA", "yokohama.png"],
  ["ZEEMAX", ""],
  ["ZEETEX", ""],
  ["ZENNA", ""],
  ["ZESTINO", ""],
  ["ZETA", ""],
]);

/** Check if a brand name (any case) is in the curated set. */
export function isCuratedBrand(name: string): boolean {
  return CURATED_BRANDS.has(name.toUpperCase());
}

/** Get local logo path for a brand, or null if not mapped. */
export function getBrandLogo(name: string): string | null {
  const file = CURATED_BRANDS.get(name.toUpperCase());
  if (!file) return null;
  return `/brand-logos/${file}`;
}
